(function(global){
  const STORE='sfc_admin_auth';
  const settings=()=>JSON.parse(localStorage.getItem('sfc_admin_settings')||'{}');
  const auth=()=>JSON.parse(localStorage.getItem(STORE)||'{}');
  const saveAuth=a=>localStorage.setItem(STORE,JSON.stringify(a));
  async function api(path,options={}){const token=auth().access_token;if(!token)throw new Error('Sign in with GitHub first.');const res=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||`GitHub API error ${res.status}`);return data;}
  async function login(){const s=settings();if(location.hash.includes('access_token=')){const p=new URLSearchParams(location.hash.slice(1));saveAuth({access_token:p.get('access_token'),created_at:Date.now()});history.replaceState(null,'',location.pathname);return;}if(!s.clientId)throw new Error('Add your GitHub OAuth Client ID in Settings before signing in.');const codeRes=await fetch('https://github.com/login/device/code',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:s.clientId,scope:'repo user'})});const code=await codeRes.json();if(!code.device_code)throw new Error(code.error_description||'GitHub device authorization failed.');window.open(code.verification_uri,'github-oauth','popup,width=720,height=760');prompt(`Enter this GitHub code on the opened authorization page:\n\n${code.user_code}\n\nAfter authorizing, click OK to continue.`);const started=Date.now();while(Date.now()-started<900000){await new Promise(r=>setTimeout(r,(code.interval||5)*1000));const tokenRes=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:s.clientId,device_code:code.device_code,grant_type:'urn:ietf:params:oauth:grant-type:device_code'})});const token=await tokenRes.json();if(token.access_token){saveAuth({...token,created_at:Date.now()});return;}if(!['authorization_pending','slow_down'].includes(token.error))throw new Error(token.error_description||'GitHub authorization failed.');}throw new Error('GitHub authorization timed out.');}
  function logout(){localStorage.removeItem(STORE);}async function getCurrentUser(){return api('/user');}
  async function getFile(path){const s=settings();return api(`/repos/${s.owner}/${s.repo}/contents/${path}?ref=${encodeURIComponent(s.branch||'main')}`);}async function putFile(path,content,message,sha){const s=settings();return api(`/repos/${s.owner}/${s.repo}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,content:btoa(unescape(encodeURIComponent(content))),sha,branch:s.branch||'main'})});}
  async function downloadGamesHTML(){const f=await getFile('games.html');return{html:decodeURIComponent(escape(atob(f.content.replace(/\n/g,'')))),sha:f.sha};}
  async function commitGamesHTML(updatedHtml,sha){return putFile('games.html',updatedHtml,'Update games from admin panel',sha);}async function downloadNotifications(){const f=await getFile('games.html');return{html:decodeURIComponent(escape(atob(f.content.replace(/\n/g,'')))),sha:f.sha};}
  async function commitNotifications(updatedHtml,sha){return putFile('games.html',updatedHtml,'Update site notification from admin panel',sha);}global.SFCGitHub={login,logout,getCurrentUser,downloadGamesHTML,commitGamesHTML,downloadNotifications,commitNotifications,hasToken:()=>!!auth().access_token,settings};
})(window);
