(function(global){
  const START='<!-- START GAMES -->', END='<!-- END GAMES -->';
  const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const unesc=s=>String(s??'').replace(/&quot;/g,'"').replace(/&gt;/g,'>').replace(/&lt;/g,'<').replace(/&amp;/g,'&');
  function extractGameSection(html){const a=html.indexOf(START),b=html.indexOf(END);if(a<0||b<0||b<a)throw new Error('games.html must contain START GAMES and END GAMES markers.');return{before:html.slice(0,a+START.length),section:html.slice(a+START.length,b),after:html.slice(b),start:a,end:b};}
  function replaceGameSection(html,newSection){const p=extractGameSection(html);return p.before+newSection+p.after;}
  function cardBlocks(section){const blocks=[];let pos=0;while(true){const open=section.indexOf('<div class="game-card"',pos);if(open<0)break;let depth=0,end=open,re=/<\/??div\b[^>]*>/gi;re.lastIndex=open;for(let m;m=re.exec(section);){if(m[0][1]==='/')depth--;else depth++;if(depth===0){end=re.lastIndex;break;}}let commentStart=section.lastIndexOf('<!--',open),prefix=open;if(commentStart>=pos&&section.slice(commentStart,open).indexOf('-->')>=0&&!section.slice(commentStart,open).trim().replace(/<!--.*?-->/s,''))prefix=commentStart;blocks.push({html:section.slice(prefix,end),cardHtml:section.slice(open,end),prefix:section.slice(prefix,open)});pos=end;}return blocks;}
  function parseBadge(html){const m=html.match(/<h3\s+class="(awardshii-btn|hotgames-btn|fixed-btn)"[^>]*>([\s\S]*?)<\/h3>/i);if(!m)return{badge:'None',badgeHtml:''};const cls=m[1],txt=m[2].replace(/<[^>]+>/g,'').trim();return{badge:cls==='awardshii-btn'?'New':cls==='hotgames-btn'?'Hot':'Fixed',badgeHtml:txt};}
  function parseGameCards(section){return cardBlocks(section).map((b,i)=>{const h=b.cardHtml;const img=(h.match(/background-image:\s*url\((['"]?)(.*?)\1\)/i)||[])[2]||'';const title=unesc(((h.match(/<h3\s+class="game-title"[^>]*>([\s\S]*?)<\/h3>/i)||[])[1]||'').replace(/<[^>]+>/g,'').trim());const a=h.match(/<a\s+[^>]*href="([^"]*)"[^>]*class="play-btn"[^>]*>([\s\S]*?)<\/a>/i)||[];return{id:`game-${i}`,index:i,title,url:unesc(a[1]||''),image:unesc(img),buttonText:unesc((a[2]||'Play Now').replace(/<[^>]+>/g,'').trim()),...parseBadge(h),html:b.html,cardHtml:h};});}
  function badgeMarkup(badge){return badge==='New'?'<h3 class="awardshii-btn">New! ✨</h3>':badge==='Hot'?'<h3 class="hotgames-btn">Hot! 🔥</h3>':badge==='Fixed'?'<h3 class="fixed-btn">Fixed 🔨</h3>':'';}
  function generateGameCard(game){const badge=badgeMarkup(game.badge);return `\n                <!-- Game: ${esc(game.title)} -->\n                <div class="game-card">\n                    <div class="game-image" style="background-image: url('${esc(game.image)}');"></div>\n                    <div class="game-info">\n                        <div style="display: flex; align-items: center; justify-content: space-between;">\n                            <h3 class="game-title">${esc(game.title)}</h3>${badge}\n                        </div>\n                        <a href="${esc(game.url)}" class="play-btn">${esc(game.buttonText||'Play Now')}</a>\n                    </div>\n                </div>\n`;}
  function serialize(games){return '\n\t\t\t\t'+games.map(g=>g.html||generateGameCard(g)).join('\n').trimEnd()+'\n\t\t\t';}
  function insertGame(section,game,index){const games=parseGameCards(section);games.splice(index??games.length,0,{...game,html:generateGameCard(game)});return serialize(games);}
  function deleteGame(section,index){const games=parseGameCards(section);games.splice(index,1);return serialize(games);}
  function moveGame(section,from,to){const games=parseGameCards(section);if(to<0||to>=games.length)return section;const [g]=games.splice(from,1);games.splice(to,0,g);return serialize(games);}
  function updateGame(section,index,game){const games=parseGameCards(section);games[index]={...games[index],...game,html:generateGameCard({...games[index],...game})};return serialize(games);}
  global.SFCParser={extractGameSection,replaceGameSection,parseGameCards,generateGameCard,insertGame,deleteGame,moveGame,updateGame};
})(window);
