(function(){
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));let state={html:'',sha:'',section:'',games:[],dirty:false};
const defaults={owner:'SchoolFlashCards5',repo:'SchoolFlashCards5.github.io',branch:'main',theme:'dark',clientId:''};
function getSettings(){return{...defaults,...JSON.parse(localStorage.getItem('sfc_admin_settings')||'{}')}}function saveSettings(s){localStorage.setItem('sfc_admin_settings',JSON.stringify(s));}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;$('#toastRegion').append(el);setTimeout(()=>el.remove(),4200)}function loading(on){$('#loadingOverlay').classList.toggle('hidden',!on)}
function page(name){$$('.page').forEach(p=>p.classList.remove('active'));$(`#${name}Page`).classList.add('active');$('#pageTitle').textContent=name[0].toUpperCase()+name.slice(1);$$('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===name));}
function refreshStats(){const g=state.games;$('#totalGames').textContent=g.length;$('#newGames').textContent=g.filter(x=>x.badge==='New').length;$('#hotGames').textContent=g.filter(x=>x.badge==='Hot').length;$('#fixedGames').textContent=g.filter(x=>x.badge==='Fixed').length;$('#recentlyUpdated').textContent=state.sha?`Loaded ${g.length} cards from games.html at ${new Date().toLocaleString()}.`:'Sync the repository to load live website data.';}
function renderGames(){const q=$('#gameSearch').value.toLowerCase();const list=$('#gamesList');list.innerHTML='';state.games.filter(g=>[g.title,g.url,g.badge].join(' ').toLowerCase().includes(q)).forEach(g=>{const row=document.createElement('article');row.className='game-row';row.innerHTML=`<div class="game-thumb" style="background-image:url('${g.image.replace(/'/g,'%27')}')"></div><div class="game-meta"><h3>${g.title}</h3><p>${g.url}</p>${g.badge!=='None'?`<span class="badge">${g.badge}</span>`:''}</div><div class="row-actions"><button class="btn" data-edit="${g.index}">Edit</button><button class="btn" data-copy="${g.index}">Duplicate</button><button class="btn" data-up="${g.index}">↑</button><button class="btn" data-down="${g.index}">↓</button><button class="btn danger" data-del="${g.index}">Delete</button></div>`;list.append(row)});$('#gamesEmpty').classList.toggle('hidden',!!list.children.length);}
function applySection(newSection){state.section=newSection;state.html=SFCParser.replaceGameSection(state.html,newSection);state.games=SFCParser.parseGameCards(newSection);state.dirty=true;refreshStats();renderGames();}
async function sync(){loading(true);try{const f=await SFCGitHub.downloadGamesHTML();state.html=f.html;state.sha=f.sha;state.section=SFCParser.extractGameSection(f.html).section;state.games=SFCParser.parseGameCards(state.section);state.dirty=false;refreshStats();renderGames();loadNotification();toast('Repository synced.')}catch(e){toast(e.message)}finally{loading(false)}}
function gameModal(game,index){const isEdit=index!==undefined;modal(`<header><h2>${isEdit?'Edit':'Add'} Game</h2><button class="btn ghost" data-close>×</button></header><form id="gameForm"><label>Game Name<input class="input" name="title" value="${game?.title||''}" required></label><label>Game URL<input class="input" name="url" value="${game?.url||''}" required></label><label>Image URL<input class="input" name="image" value="${game?.image||''}" required></label><label>Badge<select class="input" name="badge"><option>None</option><option>New</option><option>Hot</option><option>Fixed</option></select></label><label>Button Text<input class="input" name="buttonText" value="${game?.buttonText||'Play Now'}"></label><div id="livePreview" class="live-card"></div><button class="btn primary">Save</button></form>`);const form=$('#gameForm');form.badge.value=game?.badge||'None';const preview=()=>{$('#livePreview').innerHTML=`<div class="live-img" style="background-image:url('${form.image.value}')"></div><div class="live-info"><strong>${form.title.value||'Game title'}</strong><p>${form.badge.value}</p><button class="btn primary">${form.buttonText.value||'Play Now'}</button></div>`};form.oninput=preview;preview();form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const next=isEdit?SFCParser.updateGame(state.section,index,data):SFCParser.insertGame(state.section,data);applySection(next);closeModal();toast(isEdit?'Game updated.':'Game added.')}}
function modal(html){$('#modalRoot').innerHTML=`<div class="modal">${html}</div>`;$('#modalRoot').classList.remove('hidden');$$('[data-close]').forEach(b=>b.onclick=closeModal)}function closeModal(){$('#modalRoot').classList.add('hidden');$('#modalRoot').innerHTML=''}
function confirmBox(msg,yes){modal(`<header><h2>Confirm</h2><button class="btn ghost" data-close>×</button></header><p>${msg}</p><button id="confirmYes" class="btn danger">Delete</button>`);$('#confirmYes').onclick=()=>{yes();closeModal()}}
function loadNotification(){const m=state.html.match(/<h3 style="font-family: Comic Sans MS; color:red">([\s\S]*?)<\/h3>/i);$('#announcementInput').value=m?m[1].trim():'';$('#notificationPreview').innerHTML=$('#announcementInput').value;}
function notificationHtml(){return state.html.replace(/(<h3 style="font-family: Comic Sans MS; color:red">)[\s\S]*?(<\/h3>)/i,`$1\n\t\t\t${$('#announcementInput').value}\n\t\t$2`)}
async function saveGames(){loading(true);try{const r=await SFCGitHub.commitGamesHTML(state.html,state.sha);state.sha=r.content.sha;state.dirty=false;toast('games.html committed to GitHub.')}catch(e){toast(e.message)}finally{loading(false)}}async function saveNotice(){loading(true);try{state.html=notificationHtml();const r=await SFCGitHub.commitNotifications(state.html,state.sha);state.sha=r.content.sha;toast('Notification committed to GitHub.')}catch(e){toast(e.message)}finally{loading(false)}}
function initSettings(){const s=getSettings();$('#ownerInput').value=s.owner;$('#repoInput').value=s.repo;$('#branchInput').value=s.branch;$('#clientIdInput').value=s.clientId;$('#themeInput').value=s.theme;$('#currentRepo').textContent=`${s.owner}/${s.repo}@${s.branch}`;$('#githubLink').href=`https://github.com/${s.owner}/${s.repo}`;}
async function initAuth(){if(SFCGitHub.hasToken()){try{const u=await SFCGitHub.getCurrentUser();$('#currentUser').textContent=`@${u.login}`;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');sync();}catch(e){toast(e.message)}}}
window.addEventListener('hashchange',()=>page((location.hash||'#dashboard').slice(1)));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveGames();}});
$('#loginBtn').onclick=async()=>{loading(true);try{await SFCGitHub.login();await initAuth();toast('Signed in with GitHub.')}catch(e){toast(e.message)}finally{loading(false)}};$('#logoutBtn').onclick=()=>{SFCGitHub.logout();location.reload()};$('#syncBtn').onclick=sync;$('#saveGamesBtn').onclick=saveGames;$('#saveNotificationsBtn').onclick=saveNotice;$('#gameSearch').oninput=renderGames;$('#announcementInput').oninput=()=>$('#notificationPreview').innerHTML=$('#announcementInput').value;$('#saveSettingsBtn').onclick=()=>{saveSettings({owner:$('#ownerInput').value,repo:$('#repoInput').value,branch:$('#branchInput').value,clientId:$('#clientIdInput').value,theme:$('#themeInput').value});initSettings();toast('Settings saved.')};
document.body.onclick=e=>{const t=e.target;if(t.dataset.action==='add-game')gameModal();if(t.dataset.action==='edit-notification')page('notifications');if(t.dataset.action==='sync')sync();if(t.dataset.edit)gameModal(state.games[+t.dataset.edit],+t.dataset.edit);if(t.dataset.copy){const g={...state.games[+t.dataset.copy],title:state.games[+t.dataset.copy].title+' Copy'};applySection(SFCParser.insertGame(state.section,g,+t.dataset.copy+1))}if(t.dataset.up)applySection(SFCParser.moveGame(state.section,+t.dataset.up,+t.dataset.up-1));if(t.dataset.down)applySection(SFCParser.moveGame(state.section,+t.dataset.down,+t.dataset.down+1));if(t.dataset.del)confirmBox('Delete this game card from the marked games section?',()=>applySection(SFCParser.deleteGame(state.section,+t.dataset.del)))};
initSettings();page((location.hash||'#dashboard').slice(1));initAuth();
})();
